sudo: required
language: generic

services:
  - docker

before_deploy:
  - mkdir -p ~/.docker
  - echo "$DOCKER_AUTH_CONFIG" | base64 --decode > ~/.docker/config.json
  - docker info
  - docker login
  - docker build -t complex/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true complex/react-test npm test

after_success:
  - docker build -t complex/multi-client ./client
  # - docker build -t complex/multi-nginx ./nginx
  # - docker build -t complex/multi-server ./server
  # - docker build -t complex/multi-worker ./worker
  # # Log in to the docker CLI
  # # - docker login -u $DOCKER_ID --password "$DOCKER_PASSWORD"
  # # Take those images and push them to docker hub
  - docker push complex/multi-client
  # - docker push complex/multi-nginx
  # - docker push complex/multi-server
  # - docker push complex/multi-worker
