sudo: required
language: generic

services:
  - docker

before_install:
  # Ensure the .docker directory exists
  - mkdir -p ~/.docker
  # Set up Docker credentials
  - echo "Setting up Docker credentials"
  - echo "$DOCKER_AUTH_CONFIG"
  - echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json || (echo "Base64 decode failed!" && exit 1)
  - ls -l ~/.docker/config.json
  - echo "Docker config created"
  - cat ~/.docker/config.json || echo "Failed to read Docker config"

before_deploy:
  # Ensure Docker is logged in
  - docker info  # Check if Docker is properly configured
  # - docker login -u "$DOCKER_ID" --password-stdin <<< "$DOCKER_PASSWORD"  # Explicitly login if needed
  # - docker build -t complex/react-test -f ./client/Dockerfile.dev ./client  # Build Docker image

script:
  # Run tests or any other commands
  - echo "Running tests"
  # - docker run -e CI=true complex/react-test npm test

after_success:
  # Push the built Docker images to Docker Hub
  - docker build -t complex/multi-client ./client
  - docker push complex/multi-client
