sudo: required
language: generic

services:
  - docker

before_install:
  - echo "Before install step"
  
before_deploy:
  # Debugging output
  - echo "Starting before_deploy..."
  - mkdir -p ~/.docker
  - echo "DOCKER_AUTH_CONFIG: $DOCKER_AUTH_CONFIG"
  - echo "$DOCKER_AUTH_CONFIG" | base64 --decode > ~/.docker/config.json
  - echo "Docker config created."
  - docker info  # This will display info about Docker
  
  # Docker build and deploy setup
  - docker build -t complex/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "Running script..."
  - docker run -e CI=true complex/react-test npm test

after_success:
  # Docker build and push
  - docker build -t complex/multi-client ./client
  - docker push complex/multi-client
