sudo: required
language: generic

services:
  - docker

before_install:
  # Ensure the .docker directory exists
  - mkdir -p ~/.docker
  - echo "$DOCKER_AUTH_CONFIG" | base64 --decode > ~/.docker/config.json || (echo "Base64 decode failed!" && exit 1)
  - cat ~/.docker/config.json || echo "Failed to read Docker config"
  - docker build -t $DOCKER_ID/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests or any other commands
  - echo "Running tests"
  - docker run -e CI=true $DOCKER_ID/react-test npm test

after_success:
  # Push the built Docker images to Docker Hub
  - docker build -t $DOCKER_ID/multi-client ./client
  - docker build -t $DOCKER_ID/multi-nginx ./nginx
  - docker build -t $DOCKER_ID/multi-server ./server
  - docker build -t $DOCKER_ID/multi-worker ./worker
  - docker info || echo "Docker not authenticated"
  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-nginx
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'Multi-docker'
  env: 'Multi-docker-env-1'
  bucket_name: 'elasticbeanstalk-eu-north-1-034362042068'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
