name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build the Docker image for testing
      - name: Build Docker Test Image
        run: docker build -t complex/react-test -f ./client/Dockerfile.dev ./client

      # Run tests
      - name: Run Tests
        run: docker run -e CI=true complex/react-test npm test

      # Build and push images on success
      - name: Build and Push Docker Images
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Build Docker images
          docker build -t complex/multi-client ./client
          docker build -t complex/multi-nginx ./nginx
          docker build -t complex/multi-server ./server
          docker build -t complex/multi-worker ./worker

          # Log in to Docker Hub
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

          # Push Docker images to Docker Hub
          docker push complex/multi-client
          docker push complex/multi-nginx
          docker push complex/multi-server
          docker push complex/multi-worker
