name: Docker CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Test Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client

      - name: Run Tests
        run: |
          docker run \
            -e CI=true \
            ${{ secrets.DOCKER_USERNAME }}/react-test \
            npm test -- --watchAll=false --forceExit

      - name: Build and Push Docker Images
        if: success()
        run: |
          # Build Docker images
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker
          
          # Push Docker images to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-server
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker