name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image for testing
      - name: Build Docker Test Image
        run: docker build -t complex/react-test -f ./client/Dockerfile.dev ./client

      # Step 3: Run tests
      - name: Run Tests
        run: docker run -e CI=true complex/react-test npm test

      # Step 4: Build and Push Docker Images if tests succeed
      - name: Build and Push Docker Images
        if: success() # Place if before env
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Log in to Docker Hub         
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          echo "Docker username is set to: $DOCKER_USERNAME"
          docker info
          
          # Build Docker images
          docker build -t complex/multi-client ./client
          docker build -t complex/multi-nginx ./nginx
          docker build -t complex/multi-server ./server
          docker build -t complex/multi-worker ./worker
          
          # Push Docker images to Docker Hub
          docker push complex/multi-client
          docker push complex/multi-nginx
          docker push complex/multi-server
          docker push complex/multi-worker